version: '3.4'

services:
  mongo:
    image: mongo:4.4.2
    restart: always
    ports:
      - 27017:27017
  redis:
    hostname: redis
    image: redis:alpine
    ports:
      - 6379:6379
